board/config/routes.rb
Rails.application.routes.draw do

root "blogs#index"
resources :blogs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

board/app/models/blog.rb
class Blog < ApplicationRecord
end

board/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
  end

  def create
    Blog.create(
      title: params[:title],
      content: params[:content],
      image_url: params[:image_url]
    )
    redirect_to '/'
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

board/app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

board/app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

board/app/views/blogs/edit.html.erb
<h1>글수정</h1>
<%= form_tag(blog_path,method: "put")do%>
제목 <%= text_field_tag(:title)%>
내용 <%= text_field_tag(:content)%>
주소 <%= text_field_tag(:image_url)%>
<%= submit_tag("수정하기")%>
<% end %>

board/app/views/blogs/index.html.erb
<h1>홈화면입니다</h1>
<%= link_to("게시물쓰기", new_blog_path)%> <br>

<%@blogs.each do |b|%>
제목 :<%=b.title %><br>
내용 :<%=b.content%><br>
<img src="<%=b.image_url%>">
<%end%>

board/app/views/blogs/new.html.erb
<h1>글쓰기</h1>
<%= form_tag(blogs_path,method: "post")do%>
제목 <%= text_field_tag(:title)%>
내용 <%= text_field_tag(:content)%>
주소 <%= text_field_tag(:image_url)%>
<%= submit_tag("글쓰기")%>
<% end %>

board/app/views/blogs/show.html.erb
<h1>Blogs#show</h1>
<%=@blog.id%>번째 글
제목 : <%=@blog.title%>
내용 : <%=@blog.content%>
이미지 : <img src="<%=@blog.image_url%>">
<%= link_to("수정하기", edit_blog_path)%>
<%= link_to("삭제하기", blog_path,method:"DELETE")%>

board/app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

board/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>